### ISSUE TITLE
Source control build.sh output

### ISSUE THREAD

**Issue by wbeard** [billyvg/codemod-proptypes-to-flow#2]
Hi there,

It'd be really convenient to have the artifact built by build.sh source controlled. Otherwise, I have to build myself after cloning. There were also some weird permissions issues on `build.sh`. Had to `+x` in order to run.

Perhaps there's a git hook you can use to run the build task prior to merging to master?

**Comment by billyvg** [comment]
This makes sense since there's no `npm`-based flow to use the script, will do.

**Comment by wbeard** [comment]
Thanks!

**Comment by billyvg** [comment]
#4 fixed a bunch of issues related to broken env after cloning and there's no need to build when using jscodeshift
